### PR TITLE
Fix #471 Consider JAVA_HOME in tycho-document-bundle-plugin

### LINKED ISSUE #471: tycho-document-bundle-plugin tests depend on PATH
After lots of trial and error I've just found one reason for failing integration tests. The document-bundle-plugin tests run javadoc by just invoking the javadoc executable without using any path. Therefore whatever is first on the local PATH environment variable will be called. Since there are subtle differences between Java 8 (what I had on the path) and Java 11 Javadoc, the verification groovy script fails with some files not found, some files not matching content and finally even NoClassDefFoundError (for the Doclet).

What is a good way to avoid that? I can imagine these solutions:
* Somehow get the toolchain definition from maven (how?) and use that path to create a FQN
* verify the generated files to contain "Generated by javadoc (11" (which they have as HTML comment)

Any better ideas?

### PR DESCRIPTION
**Pull request by Bananeweizen**
Use also JAVA_HOME to find a suitable javadoc executable. That logic is
similar to what plexus JavacCompiler does.

Tested locally on Windows. Not sure how to have an actual integration test for this change.

### CODE REVIEW

File: tycho-extras/tycho-document-bundle-plugin/src/main/java/org/eclipse/tycho/extras/docbundle/JavadocRunner.java [hunk 1]
```diff
@@ -33,294 +33,312 @@
...
+			javadocFromJavaHome += ".exe";
+		}
+
+		log.debug("Testing javadoc from java.home = " + javadocFromJavaHome);
+
+		if (new File(javadocFromJavaHome).canExecute()) {
+			return javadocFromJavaHome;
+		}
+
+		// use JAVA_HOME
```
Comment (Bananeweizen) [inline tycho-extras/tycho-document-bundle-plugin/src/main/java/org/eclipse/tycho/extras/docbundle/JavadocRunner.java:303]: lines 303 to 317 are the actual change. Not sure what lead to showing everything as diff.

Comment (laeubi) [reply tycho-extras/tycho-document-bundle-plugin/src/main/java/org/eclipse/tycho/extras/docbundle/JavadocRunner.java:303]: never mind, I think this is due to changed formatting settings.

**Review by laeubi — APPROVED** [review]
Looks good to me and as it does not break any existing code and is more close to `maven-javadoc-plugin` I think it is fine.

As this slightly can change behavior we probably want to add a hint to the release notes, but I'm not sure how widely used this mojo actually is.

**Comment by mickaelistria** [comment]
Thanks!
