### PR TITLE
tycho-eclipserun-plugin: Use <applicationsArgs> literally

### LINKED ISSUE #1009: tycho-eclipserun-plugin: Individual arguments inside <applicationsArgs> are incorrectly parsed again
Consider

```
          <plugin>
            <groupId>org.eclipse.tycho.extras</groupId>
            <artifactId>tycho-eclipserun-plugin</artifactId>
            <version>2.7.3</version>
            <executions>
              <execution>
                <id>do-something</id>
                <goals>
                  <goal>eclipse-run</goal>
                </goals>
                <phase>package</phase>
                <configuration>
                  <applicationsArgs>
                    <applicationsArgs>arg1</args>
                    <applicationsArgs>literal arg with spaces</args>
                    <applicationsArgs>argument'with'literalquotes</args>
                  </applicationsArgs>
                </configuration>
                </configuration>
              </execution>
            </executions>
          </plugin>
```

Expected command line arguments of the final process:

```
arg1
literal arg with spaces
argument'with'literalquotes
```

Actual command line arguments of the final process:
```
arg1
literal
arg
with
spaces
argumentwithliteralquotes
```

This is because https://github.com/eclipse/tycho/blob/dfb97c8103c5d59f2cc3ee7227ca27ffde9d83b9/tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java#L407 performs `splitArgLine()` on the already individual arguments.

The old legacy `appArgLine` which behaved like that has already been removed in 053b82b20a0958f935296a58390eb2ab8df2abd3. 

The whole reason why a single string  `appArgLine` was deprecated / removed and replaced with list-based `<applicationsArgs>` was to have full control over the way arguments are passed in.

I propose to change / fix the handling of `<applicationsArgs>` for Tycho 3.0 by not re-interpreting the values any longer.

### PR DESCRIPTION
**Pull request by sratz**
List-based `<applicationsArgs>` was introduced as a more deterministic
replacement to the old single-string-based `<appArgLine>` to have full
control over the arguments.

The old `<appArgLine>` has already been removed in
053b82b20a0958f935296a58390eb2ab8df2abd3.

However, even the individual entries of `<applicationsArgs>` are still
interpreted via `splitArgLine()`.

Remove this `splitArgLine()` handling and treat the arguments literally.

This is now symmetrical to the list-based `<jvmArgs>`, which already
treats elements literally.

Also adjust JavaDoc to use singular `<arg>` for the individual elements.

Fixes #1009

### CODE REVIEW

**Comment by Bananeweizen** [comment]
To me the change looks good. I'm just wondering if we could also rename `applicationsArgs` to `applicationArgs` at the same time, if we are doing incompatible changes anyway. I'm not a native speaker, but the first one seems wrong with its plural form of `applications`.

File: tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java [hunk 1]
```diff
@@ -151,8 +150,8 @@ public class EclipseRunMojo extends AbstractMojo {
 	 * 
 	 * <pre>
 	 * &lt;jvmArgs&gt;
-	 *   &lt;args&gt;-Xdebug&lt;/args&gt;
-	 *   &lt;args&gt;-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044&lt;/args&gt;
+	 *   &lt;arg&gt;-Xdebug&lt;/arg&gt;
```
Comment (akurtakov) [inline tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java:153]: When you edit such javadoc would you please make it :
```
{@code
<jvmArgs>
	 <args>-Xdebug</args>
	   <args>-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044</args>
 </jvmArgs>
 }
```
That makes it far more readable.

File: tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java [hunk 2]
```diff
@@ -172,8 +171,8 @@ public class EclipseRunMojo extends AbstractMojo {
 	 * 
 	 * <pre>
 	 * &lt;applicationsArgs&gt;
-	 *   &lt;args&gt;-buildfile&lt;/args&gt;
-	 *   &lt;args&gt;build-test.xml&lt;/args&gt;
+	 *   &lt;arg&gt;-buildfile&lt;/arg&gt;
```
Comment (akurtakov) [inline tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java:174]: Same comment about javadoc readability in the code.

File: tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java (hunk 1 above)
Comment (akurtakov) [reply tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java:153]: Fine with me.

Comment (mickaelistria) [reply tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java:153]: You cna use `@Parameter(alias="applicationsArgs")` to keep compatibility while renaming the field.

File: tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java (hunk 2 above)
Comment (sratz) [reply tycho-extras/tycho-eclipserun-plugin/src/main/java/org/eclipse/tycho/extras/eclipserun/EclipseRunMojo.java]: Done

**Comment by mickaelistria** [comment]
Thanks!
