### PR TITLE
Fix #261 BaselineValidator.validateAndReplace() fails with UnsupportedOperationException under Maven 3.8.2

### LINKED ISSUE #261: BaselineValidator.validateAndReplace() fails with UnsupportedOperationException under Maven 3.8.2
When using Maven 3.8.2 Tycho's `P2MetadataMojo` or `P2MetadataDefaultMojo` in version 2.4.0 (it is very likely the same for Tycho 2.5.0-SNAPSHOT because the class did not change) `BaselineValidator.validateAndReplace()` fails by throwing an `UnsupportedOperationException` when it attempts to remove an element from the list returned by `project.getAttachedArtifacts()` because the corresponding artifact is not present in the baseline.

As of Maven 3.8.2 `MavenProject.getAttachedArtifacts()` returns an unmodifiable List.
This was changed as part of the fix of [MNG-5868](https://issues.apache.org/jira/browse/MNG-5868) which was merged into the Maven master https://github.com/apache/maven/pull/358 and back-ported into the 3.8. stream as commit 66a43813770cd7dee9eb1ed0372e3f784ba0c541 (did not found the PR).

Unfortunately I did not found an alternative to remove attached artifacts from a MavenProjects.

### PR DESCRIPTION
**Pull request by laeubi**
Signed-off-by: Christoph Läubrich <laeubi@laeubi-soft.de>

### CODE REVIEW

**Comment by laeubi** [comment]
FYI @HannesWell

**Comment by laeubi** [comment]
FYI @sbouchet

File: tycho-p2/tycho-p2-plugin/src/main/java/org/eclipse/tycho/plugins/p2/BaselineValidator.java [hunk 1]
```diff
@@ -145,8 +148,21 @@ public String getDetailedMessage() {
...
-                                    iterator.remove();
+                                Artifact next = iterator.next();
+                                if (classifier.equals(next.getClassifier())) {
+                                    try {
+                                        iterator.remove();
+                                    } catch (UnsupportedOperationException e) {
+                                        ArrayList<Artifact> list = new ArrayList<>(attachedArtifacts);
+                                        list.remove(next);
+                                        try {
+                                            MethodUtils.invokeMethod(project, true, "setAttachedArtifacts", list);
```
Comment (HannesWell) [inline tycho-p2/tycho-p2-plugin/src/main/java/org/eclipse/tycho/plugins/p2/BaselineValidator.java:159]: Doesn't this cause an illegal reflective access error when the build is performed on a Java-17 VM?

Comment (laeubi) [reply tycho-p2/tycho-p2-plugin/src/main/java/org/eclipse/tycho/plugins/p2/BaselineValidator.java:159]: Then this workaround won't work of course, but tycho does not work in all combinations of build vm and maven version anyways.

Comment (HannesWell) [reply tycho-p2/tycho-p2-plugin/src/main/java/org/eclipse/tycho/plugins/p2/BaselineValidator.java:159]: But I think the combination of latest Java, latest Maven and latest Tycho is not some special niche configuration but one that should work. Especially because Users are always encouraged to use the latest versions, which I think is good. But then Tycho should support it.

Comment (laeubi) [reply tycho-p2/tycho-p2-plugin/src/main/java/org/eclipse/tycho/plugins/p2/BaselineValidator.java:159]: One could still use latest java to compile, but feel free to suggest a better alternative here :-)

Comment (HannesWell) [reply tycho-p2/tycho-p2-plugin/src/main/java/org/eclipse/tycho/plugins/p2/BaselineValidator.java:159]: Unfortunately I don't have a better solution immediately at hand.
I know this is not very helpful to find a solution for the moment, but I think it is a point to mention and to consider for the future.

Comment (laeubi) [reply tycho-p2/tycho-p2-plugin/src/main/java/org/eclipse/tycho/plugins/p2/BaselineValidator.java:159]: This mojo was designed in 2012 so many assumptions of it might not hold true for modern java, at least this allows to use it for some more time until we find a better solution e.g. convince maven to make the method public, provide an alternative approach to remove artifacts or even overhaul the BaseLineVlidator to use a different approach. Even though most eclipse-project use this, I have never seen a use of it before in any other tycho project so maybe this is also a bit eclipse-specific and the default ci-servers use java 11 to build afaik so there is some time to investigate for better solutions until then.

**Comment by laeubi** [comment]
@mickaelistria @akurtakov any comments?

**Comment by laeubi** [comment]
Cherry picked to 2.5.x as well
